### ISSUE TITLE
outdated encryption method on this repository

### ISSUE THREAD

**Issue by Sa1tama228** [timelis/Instagram-Encrypted-Password#4]
would you like to update it?

your enc:
#PWD_INSTAGRAM:1:1729774785:ASncpwttXCzmpS190xYAAbx1FfpjoBJ3bOf/s+7YEyLWRoVpc81XZXfGN7WXzzbC+ufufSiMmPjRii6M2JjapG4fu6Fl8YKP0cq5x7aM9pL+DJj6zgF99/tJeTFpqAS4jS3pOzgOicMpVGNgm2d3MMhCrODQ2q4sBcUsJUOUiJhIw9UMNUEaHjO5h/kIwvrc1mKMLYZl2GNm7GnRjbzCAHs3ykIX9IQ6XVT9ZBChTzGY4tBRKdN3GnBl9GZe5E7WQRlbWqmGbHDuHRdgFP0IDkdNbHWEAiu5DX+gs9/JICAZJCuPUaPXBMvuJZ41L7OlKuErqxshDpIalKQt423WTlmrdAaB/6l1Qj7Cx1ds6PmfWpCGcCwdGFIW7q5OC2m2rQgtXsvhBdBK4Hzn
actual enc:
#PWD_INSTAGRAM_BROWSER:10:1729774784:Af9QAJsDTt2BbGQj69d/kMwiRGtHLfSRiuONnZNVrs4dUQt5pbNKRo3qwD9hhCaVisoLb0IA9hVQ0LMqdVwUvznzv6j4UMG68RhEvlQbbswwt9KZ+XxQ+cZw0uPNvZyUamFONHO2UNH7lMMdj2oWAw==

password: 228Satana228

**Comment by timelis** [comment]
Am I understanding this repository correctly?

**Comment by timelis** [comment]
If we don't hear back by today, we will close the issue as resolved.

**Comment by bondobrus** [comment]
Instagram still uses old. The code is working. For login I have seen they currently using version 4 instead 1 (309 app version)

@timelis is there any way to contact you? On mail or somewhere else.

**Comment by timelis** [comment]
I confirm that type 1 is used in version 320.

As explained in this repository, type 1 is used only under the following conditions:
When you log in or register on a new device (a device that has never been logged into any account before)

I probably can't help you with anything, but here's my contact info:
Discord: ppop0635
