### ISSUE TITLE
pubkey changes on new login request

### ISSUE THREAD

**Issue by makovez** [timelis/Instagram-Encrypted-Password#5]
Hi, i noticed that a new pubkey is received when a new login request is sent. In this case do we need to update the pub key ?

Did you get this pubkey from the login response or was it inside the apk ? I'm trying with version 336

**Comment by timelis** [comment]
How did you clarify and test that?

**Comment by timelis** [comment]
https://github.com/timelis/Instagram-Encrypted-Password/issues/4

A similar issue was confirmed before, but it seems to have been a mistake.
I would only investigate if there was a genuine possibility that the public key had been changed.

**Comment by timelis** [comment]
I haven’t done any Instagram analysis for over a year.
So it's quite possible that the specs have changed.
However, analyzing Instagram is a very difficult task for me at the moment. I would rather not do it if possible.

So please explain the changes so I can understand them.

**Comment by makovez** [comment]
Hi, thanks for your quick reply. There isn't a clear proof that this is changing as I haven't tested it. But as you can see in the response of the login, a new Pub Key is returned. 

![immagine](https://github.com/user-attachments/assets/7ffa821d-bdd8-4fb0-aee4-adc5a4ab75b4)

**Comment by timelis** [comment]
Please share the network request you want to reproduce

**Comment by makovez** [comment]
This is the response to the login request.

**Comment by timelis** [comment]
If you are having that request fail then I think you need to update, if it's not failing then you don't need to update

I don't have an Android device right now, so I can't check in detail, but the public key included in the apk has not been updated.

**Comment by makovez** [comment]
Ok thanks can you give the specific version and the path where did u find the pub key in the apk?

I haven't yet tried your pub key request, I'm just saying that when login request is sent. The response contains a new pub key and key number.

**Comment by Sunda001** [comment]
> Ok thanks can you give the specific version and the path where did u find the pub key in the apk?
> 
> I haven't yet tried your pub key request, I'm just saying that when login request is sent. The response contains a new pub key and key number.

![IMG_20241213_223043_637.jpg](https://github.com/user-attachments/assets/5c1f89cb-c669-48b0-b32e-d9935a8510e7)

**Comment by makovez** [comment]
![immagine](https://github.com/user-attachments/assets/fb16a664-a33c-4de6-9b47-76ce076a3e31)
I think this behaviour should be investigated. 
Maybe after first login, the server expects you to update the pub_key and key_id ?

**Comment by timelis** [comment]
What version of the password is actually used for login (or account creation)?

I verified with version 298 a year ago, and the request you shared has been done since then!
But the actual encryption being used is version 1.

**Comment by timelis** [comment]
What is important is not the response to that request, but the actual version of encryption used. That's all.

**Comment by makovez** [comment]
#PWD_INSTAGRAM:1:1734041305:ASmAzpxwvLPJbjOO7ugAAWlc8rwQQUk7YJ3ASOTpLbBGnAYWULMGVGlqzn+nsOrNSHTDLQTbiHwULF+kmP5u90m9GVo9ynf/MZw4cxi36WYtJb8rgMO3hCJ9HWbmWIKXVEY0UGzOLWgjQx0Ql96elFZnnzroWRGRXg3ETSLX2bg7QzPlRIBG8qLgEq5D9MA9N3lWjerLPQPnDv8SuIG2ux8vXG5DUD+H8N7GNUJKGy5Rp0RMGa67m9exp6HAoFkLCBhF4uB+/WgsqXhif4i7Mi5NRCT1Cq1TxXL29W7vEOH40OCDIFc/yMmS8NtS2tmL5Y+AHqhC4WSgMevuNp3F7EMHwFUOKC9E9z5FY5jgFHFmUXZw87l/Xn02twqFHC/WH7yfXu0tFGwB0FVS/PfIQ6AY

This is the encryption version. Which is the same as yours. But I am saying that it might be that the PUB KEY and KEY_ID_VERSION used to encrypt the password might be not the same as yours. 

Because the response to that request with the new PUBKEY and KEY_ID suggests it might change.

**Comment by timelis** [comment]
I understand what you are trying to explain, but I need an Android device to test it. I don't have an Android device right now, so I can't test it.

**Comment by timelis** [comment]
The apk has a function to encrypt the password, and the function contains the Key ID and Public Key. I found the public key in the function.

Although I have confirmed that the encryption function exists in version 361, I don't know if the function is actually called. I don't have an actual Android device so I can't test it.
The last time I saw that function being called was version 300.

**Comment by makovez** [comment]
I have an Android device if you want we can text in telegram my user id: @sbonggo t.me/sbonggo

If i can know the function name I can mock that with Frida and see if it is being called.

**Comment by timelis** [comment]
I think it would be quicker to just run my code and see if it logs you in successfully.

**Comment by makovez** [comment]
works
